/* eslint-disable object-curly-newline */

// API
 const API = 'https://gzus.contetecnologia.com.br/api/public/api';
//const API = 'http://localhost/Conte-tecnologia/GZUZ/api/public/api';

// Redux Auth Slice
const REGISTER_USER_AUTH_SLICE = `${API}/usuario/cadastrar`;
const LOGIN_USER_AUTH_SLICE = `${API}/login`;

// Redux Orders Slice
const LIST_ORDERS_SLICE = `${API}/usuario/ordem/minhas-ordens?usuario=`;
const CREATE_ORDER_SLICE = `${API}/usuario/ordem/cadastrar`;
const CANCEL_ORDER_SLICE = `${API}/usuario/ordem/cancelamento`;

// HEADER MAIN
const BTN_LOGIN = 'MAIN.BTN_LOGIN';
const BTN_REGISTER = 'MAIN.BTN_REGISTER';
const BTN_HOME = 'MAIN.BTN_HOME';
const BTN_COURIER = 'MAIN.BTN_COURIER';
const BTN_CONSULTING = 'MAIN.BTN_CONSULTING';
const BTN_HELPING_LIVES = 'MAIN.BTN_HELPING_LIVES';
const BTN_CONTACT_US = 'MAIN.BTN_CONTACT_US';

//MAIN
const TITLE_MAIN = 'MAIN.TITLE';
const LOGISTIC_MAIN = 'MAIN.LOGISTIC';
const CONTENT_MAIN = 'MAIN.CONTENT';

// FLAGS
const TEXT_FLAG_PT = 'MAIN.TEXT_FLAG_PT';
const TEXT_FLAG_EN = 'MAIN.TEXT_FLAG_EN';
const TEXT_FLAG_ES = 'MAIN.TEXT_FLAG_ES';

// LOGIN
const LABEL_PASSWORD = 'LOGIN.LABEL_PASSWORD';
const FORGOT_PASSWORD = 'LOGIN.FORGOT_PASSWORD';
const BTN_ENTER = 'LOGIN.BTN_ENTER';
const BTN_BACK = 'LOGIN.BTN_BACK';
const LOGIN_MSG_ERROR = 'LOGIN.MSG_ERROR';

// REGISTER

const BTN_DRIVER = 'REGISTER.BTN_DRIVER';
const BTN_USER = 'REGISTER.BTN_USER';
const LABEL_REGISTER = 'REGISTER.LABEL_REGISTER';
const LABEL_COMPANY = 'REGISTER.LABEL_COMPANY';
const LABEL_NAME = 'REGISTER.LABEL_NAME';
const LABEL_EMAIL = 'REGISTER.LABEL_EMAIL';
const LABEL_PHONE = 'REGISTER.LABEL_PHONE';
const ADD_MORE_USERS = 'REGISTER.ADD_MORE_USERS';
const LABEL_ADRESS = 'REGISTER.LABEL_ADRESS';
const LABEL_ZIPCODE = 'REGISTER.LABEL_ZIPCODE';
const LABEL_CITY = 'REGISTER.LABEL_CITY';
const LABEL_STATE = 'REGISTER.LABEL_STATE';
const LABEL_COUNTRY = 'REGISTER.LABEL_COUNTRY';
const LABEL_PASSWORD_REGISTER = 'REGISTER.LABEL_PASSWORD';
const LABEL_CONFIRM_PASSWORD = 'REGISTER.LABEL_CONFIRM_PASSWORD';
const BTN_REGISTER_REGISTER = 'REGISTER.BTN_REGISTER';
const BTN_BACK_REGISTER = 'REGISTER.BTN_BACK';
const REGISTER_MSG_EMPTY_FIELDS = 'REGISTER.MSG_EMPTY_FIELDS';
const REGISTER_MSG_PASSWORD_NOT_MATCH = 'REGISTER.MSG_PASSWORD_NOT_MATCH';
const REGISTER_MSG_USER_REGISTERED_SUCCESS = 'REGISTER.MSG_USER_REGISTERED_SUCCESS';
const REGISTER_MSG_USER_REGISTERED_ERROR = 'REGISTER.MSG_USER_REGISTERED_ERROR';

// ROUTE NOT FOUND
const ROUTE_NOT_FOUND_TITLE = 'ROUTE_NOT_FOUND.TITLE';
const ROUTE_NOT_FOUND_CONTENT = 'ROUTE_NOT_FOUND.CONTENT';
const ROUTE_NOT_FOUND_BTN_BACK = 'ROUTE_NOT_FOUND.BTN_BACK';

//  HOME USERS
const BTN_CREATE_ORDER = 'HOME_USERS.BTN_CREATE_ORDER';

//  ORDERSs
const STATUS_OPEN = 'ORDERS.STATUS_OPEN';
const STATUS_PROGRESS = 'ORDERS.STATUS_PROGRESS';
const STATUS_COMPLETE = 'ORDERS.STATUS_COMPLETE';
const STATUS_CANCELED = 'ORDERS.STATUS_CANCELED';
const STATUS_QUEUED = 'ORDERS.STATUS_QUEUED';
const TITLE_ORDERS = 'ORDERS.TITLE_ORDERS';
const TITLE_DATE = 'ORDERS.TITLE_DATE';
const TITLE_FROM = 'ORDERS.TITLE_FROM';
const TITLE_TO = 'ORDERS.TITLE_TO';
const TITLE_DRIVER = 'ORDERS.TITLE_DRIVER';
const TITLE_USER = 'ORDERS.TITLE_USER';
const TITLE_LOAD = 'ORDERS.TITLE_LOAD';
const BTN_SEE_MORE = 'ORDERS.BTN_SEE_MORE';
const LABEL_YOUR_DELIVERIES = 'ORDERS.LABEL_YOUR_DELIVERIES';

// ORDER DETAIL
const PATH_SEE_MORE = 'ORDER_DETAILS.PATH_SEE_MORE';
const PATH_HOME = 'ORDER_DETAILS.PATH_HOME';
const TITLE_OPEN_REQUEST = 'ORDER_DETAILS.TITLE_OPEN_REQUEST';
const MSG_UNANSWERED = 'ORDER_DETAILS.MSG_UNANSWERED';
const TITLE_PICKUP = 'ORDER_DETAILS.TITLE_PICKUP';
const TITLE_DROPOFF = 'ORDER_DETAILS.TITLE_DROPOFF';
const MSG_PICKUP_DETAILS = 'ORDER_DETAILS.MSG_PICKUP_DETAILS';
const TITLE_BILL_TO = 'ORDER_DETAILS.TITLE_BILL_TO';
const TITLE_DATE_ORDER_DETAIL = 'ORDER_DETAILS.TITLE_DATE';
const TITLE_TIME = 'ORDER_DETAILS.TITLE_TIME';
const TITLE_COMPANY_NAME = 'ORDER_DETAILS.TITLE_COMPANY_NAME';
const TITLE_EMAIL = 'ORDER_DETAILS.TITLE_EMAIL';
const TITLE_PHONE = 'ORDER_DETAILS.TITLE_PHONE';
const TITLE_ADRESS = 'ORDER_DETAILS.TITLE_ADRESS';
const TITLE_ZIPCODE = 'ORDER_DETAILS.TITLE_ZIPCODE';
const TITLE_CITY = 'ORDER_DETAILS.TITLE_CITY';
const TITLE_STATE = 'ORDER_DETAILS.TITLE_STATE';
const TITLE_DELIVERY_DETAILS = 'ORDER_DETAILS.TITLE_DELIVERY_DETAILS';
const TITLE_CONTACT_NAME = 'ORDER_DETAILS.TITLE_CONTACT_NAME';
const TITLE_ORDER_DETAILS = 'ORDER_DETAILS.TITLE_ORDER_DETAILS';
const TITLE_BTN_CANCEL_ORDER = 'ORDER_DETAILS.TITLE_BTN_CANCEL_ORDER';
const TITLE_BTN_EDIT_OFFER = 'ORDER_DETAILS.TITLE_BTN_EDIT_OFFER';
const ORDER_DETAILS_BTN_BACK = 'ORDER_DETAILS.BTN_BACK';
const ORDER_DETAILS_MSG_CANCELED_ORDER = 'ORDER_DETAILS.MSG_CANCELED_ORDER';

// MODAL NEW OFFER
const TITLE_NEW_OFFER = 'MODAL_NEW_OFFER.TITLE';
const MSG_WILL_CHANGE = 'MODAL_NEW_OFFER.MSG_WILL_CHANGE';
const MSG_FOR_SERVICE = 'MODAL_NEW_OFFER.MSG_FOR_SERVICE';
const BTN_ACCEPT_OFFER = 'MODAL_NEW_OFFER.BTN_ACCEPT_OFFER';
const BTN_CANCEL_OFFER = 'MODAL_NEW_OFFER.BTN_CANCEL_OFFER';
const MODAL_NEW_OFFER_LABEL_PICKUP = 'MODAL_NEW_OFFER.LABEL_PICKUP';
const MODAL_NEW_OFFER_LABEL_DROPOFF = 'MODAL_NEW_OFFER.LABEL_DROPOFF';

// MODAL CANCEL ORDER
const TITLE_CANCEL_ORDER = 'MODAL_CANCEL_ORDER.TITLE';
const MSG_CANCEL = 'MODAL_CANCEL_ORDER.MSG_CANCEL';
const BTN_AWARE = 'MODAL_CANCEL_ORDER.BTN_AWARE';
const TITLE_ORDER_CANCELED = 'MODAL_CANCEL_ORDER.TITLE_ORDER_CANCELED';
const MSG_ORDER_CANCELED = 'MODAL_CANCEL_ORDER.MSG_ORDER_CANCELED';
const MSG_OPTIONAL_CAR = 'MODAL_CANCEL_ORDER.MSG_OPTIONAL_CAR';
const MSG_OPTIONAL_DRIVER = 'MODAL_CANCEL_ORDER.MSG_OPTIONAL_DRIVER';
const MSG_OPTIONAL_PLACE = 'MODAL_CANCEL_ORDER.MSG_OPTIONAL_PLACE';
const MSG_OPTIONAL_DATES = 'MODAL_CANCEL_ORDER.MSG_OPTIONAL_DATES';
const MSG_OPTIONAL_RUDE = 'MODAL_CANCEL_ORDER.MSG_OPTIONAL_RUDE';
const MSG_OPTIONAL_OTHER = 'MODAL_CANCEL_ORDER.MSG_OPTIONAL_OTHER';
const BTN_SEND = 'MODAL_CANCEL_ORDER.BTN_SEND';

// NEW ORDER
const BREAD_CRUMBS_NEW_ORDER = 'NEW_ORDER.BREAD_CRUMBS';

// STEP CREATE ORDERS PICKUP DETAILS
const LABEL_BILL_TO_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_BILL_TO_PICKUP';
const LABEL_DATE_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_DATE_PICKUP';
const LABEL_TIME_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_TIME_PICKUP';
const LABEL_COMPANY_NAME_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_COMPANY_NAME_PICKUP';
const LABEL_EMAIL_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_EMAIL_PICKUP';
const LABEL_PHONE_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_PHONE_PICKUP';
const LABEL_ADRESS_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_ADRESS_PICKUP';
const LABEL_ZIPCODE_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_ZIPCODE_PICKUP';
const LABEL_CITY_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_CITY_PICKUP';
const LABEL_STATE_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_STATE_PICKUP';
const LABEL_CONTACT_NAME_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.LABEL_CONTACT_NAME_PICKUP';
const BTN_NEXT_PICKUP = 'STEP_CREATE_ORDERS_PICKUP.BTN_NEXT_PICKUP';

// STEP CREATE ORDERS DELIVERY
const LABEL_DATE_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_DATE_DELIVERY';
const LABEL_TIME_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_TIME_DELIVERY';
const LABEL_COMPANY_NAME_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_COMPANY_NAME_DELIVERY';
const LABEL_EMAIL_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_EMAIL_DELIVERY';
const LABEL_PHONE_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_PHONE_DELIVERY';
const LABEL_ADRESS_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_ADRESS_DELIVERY';
const LABEL_ZIPCODE_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_ZIPCODE_DELIVERY';
const LABEL_CITY_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_CITY_DELIVERY';
const LABEL_STATE_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_STATE_DELIVERY';
const LABEL_CONTACT_NAME_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.LABEL_CONTACT_NAME_DELIVERY';
const BTN_NEXT_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.BTN_NEXT_DELIVERY';
const BTN_BACK_DELIVERY = 'STEP_CREATE_ORDERS_DELIVERY.BTN_BACK_DELIVERY';

// STEP CREATE ORDERS ORDERS DETAILS
const TITLE_PICKING_UP_01 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PICKING_UP_01';
const TITLE_PICKING_UP_02 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PICKING_UP_02';
const TITLE_PICKING_UP_03 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PICKING_UP_03';
const TITLE_PICKING_UP_04 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PICKING_UP_04';
const TITLE_DIMENSIONS_01 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_DIMENSIONS_01';
const TITLE_DIMENSIONS_02 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_DIMENSIONS_02';
const TITLE_DIMENSIONS_03 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_DIMENSIONS_03';
const TITLE_DIMENSIONS_04 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_DIMENSIONS_04';
const TITLE_CARGO = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_CARGO';
const DIMENSION_FEET = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.DIMENSION_FEET';
const DIMENSION_CENTIMETER = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.DIMENSION_CENTIMETER';
const DIMENSION_LBS = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.DIMENSION_LBS';
const DIMENSION_KGS = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.DIMENSION_KGS';
const TOTAL_WEIGHT = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TOTAL_WEIGHT';
const LABEL_HIGHT = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.LABEL_HIGHT';
const LABEL_WIDTH = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.LABEL_WIDTH';
const LABEL_DEPTH = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.LABEL_DEPTH';
const LABEL_WEIGHT = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.LABEL_WEIGHT';
const BTN_TAKE_PICTURE = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.BTN_TAKE_PICTURE';
const TITLE_PURCHASE_ORDER_01 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PURCHASE_ORDER_01';
const TITLE_PURCHASE_ORDER_02 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PURCHASE_ORDER_02';
const TITLE_PURCHASE_ORDER_03 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PURCHASE_ORDER_03';
const TITLE_PURCHASE_ORDER_04 = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_PURCHASE_ORDER_04';
const LABEL_INVOICE_NUMBER = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.LABEL_INVOICE_NUMBER';
const TITLE_OBSERVATION = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_OBSERVATION';
const LABEL_OBSERVATION = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.LABEL_OBSERVATION';
const SELECT_TYPE_CARGO = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.SELECT_TYPE_CARGO';
const SELECT_TYPE_DOCS = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.SELECT_TYPE_DOCS';
const SELECT_TYPE_CARGO_DOCS = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.SELECT_TYPE_CARGO_DOCS';
const BTN_NEXT_ORDERS_ORDERS_DETAIL =
  'STEP_CREATE_ORDERS_ORDERS_DETAILS.BTN_NEXT_ORDERS_ORDERS_DETAIL';
const BTN_BACK_ORDERS_ORDERS_DETAIL =
  'STEP_CREATE_ORDERS_ORDERS_DETAILS.BTN_BACK_ORDERS_ORDERS_DETAIL';
  const TITLE_TOTAL_OBJ = 'STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_TOTAL_OBJ';
  const TITLE_VOLUME = "STEP_CREATE_ORDERS_ORDERS_DETAILS.TITLE_VOLUME";
  const BTN_TITLE_BUTTOM_IMAGE_DOWNLOAD = "STEP_CREATE_ORDERS_ORDERS_DETAILS.BTN_TITLE_BUTTOM_IMAGE_DOWNLOAD"

// STEP CREATE ORDERS CONFIRMATION
const TITLE_CONFIRMATION_PICKUP_DETAILS =
  'STEP_CREATE_ORDERS_CONFIRMATION.TITLE_CONFIRMATION_PICKUP_DETAILS';
const TITLE_CONFIRMATION_DELIVERY_DETAILS =
  'STEP_CREATE_ORDERS_CONFIRMATION.TITLE_CONFIRMATION_DELIVERY_DETAILS';
const TITLE_CONFIRMATION_ORDER_DETAILS =
  'STEP_CREATE_ORDERS_CONFIRMATION.TITLE_CONFIRMATION_ORDER_DETAILS';
const LABEL_BILL_TO_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_BILL_TO_CONFIRMATION';
const LABEL_DATE_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_DATE_CONFIRMATION';
const LABEL_TIME_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_TIME_CONFIRMATION';
const LABEL_COMPANY_NAME_CONFIRMATION =
  'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_COMPANY_NAME_CONFIRMATION';
const LABEL_CONTACT_NAME_CONFIRMATION =
  'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CONTACT_NAME_CONFIRMATION';
const LABEL_EMAIL_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_EMAIL_CONFIRMATION';
const LABEL_PHONE_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_PHONE_CONFIRMATION';
const LABEL_ADRESS_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_ADRESS_CONFIRMATION';
const LABEL_CITY_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CITY_CONFIRMATION';
const LABEL_STATE_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_STATE_CONFIRMATION';
const LABEL_ZIPCODE_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_ZIPCODE_CONFIRMATION';
const BTN_FINISH_ORDER = 'STEP_CREATE_ORDERS_CONFIRMATION.BTN_FINISH_ORDER';
const TITLE_CONFIRMATION_PROOF_DELIVERY =
  'STEP_CREATE_ORDERS_CONFIRMATION.TITLE_CONFIRMATION_PROOF_DELIVERY';
const LABEL_ATTACH_DOCS = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_ATTACH_DOCS';
const BTN_CONFIRMATION_UPLOAD_DOCS = 'STEP_CREATE_ORDERS_CONFIRMATION.BTN_CONFIRMATION_UPLOAD_DOCS';
const LABEL_ATTACH_PICTURES_CARGO = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_ATTACH_PICTURES_CARGO';
const LABEL_CONTATCT_SIGNTURE = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CONTATCT_SIGNTURE';
const LABEL_CONFIRMATION_NAME = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CONFIRMATION_NAME';
const LABEL_CONFIRMATION_DATE = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CONFIRMATION_DATE';
const LABEL_CONFIRMATION_TIME = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CONFIRMATION_TIME';
const LABEL_CONFIRMATION_LOCATION = 'STEP_CREATE_ORDERS_CONFIRMATION.LABEL_CONFIRMATION_LOCATION';
const BTN_BACK_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.BTN_BACK_CONFIRMATION';
const BTN_NEW_ORDER_CONFIRMATION = 'STEP_CREATE_ORDERS_CONFIRMATION.BTN_NEW_ORDER_CONFIRMATION';
const MSG_CREATE_SUCCESS_ORDER_CONFIRMATION =
  'STEP_CREATE_ORDERS_CONFIRMATION.MSG_CREATE_SUCCESS_ORDER_CONFIRMATION';
const MSG_CREATE_FAILED_ORDER_CONFIRMATION =
  'STEP_CREATE_ORDERS_CONFIRMATION.MSG_CREATE_FAILED_ORDER_CONFIRMATION';

// STEPS NAMES
const STEP_PICKUP_DETAILS = 'STEPS_NAMES.STEP_PICKUP_DETAILS';
const STEP_DELIVERY_DETAILS = 'STEPS_NAMES.STEP_DELIVERY_DETAILS';
const STEP_ORDERS_DETAILS = 'STEPS_NAMES.STEP_ORDERS_DETAILS';
const STEP_CONFIRMATION = 'STEPS_NAMES.STEP_CONFIRMATION';

// Register Drivers
const REGISTER_DRIVERS_TITLE = 'REGISTER_DRIVER.TITLE_REGISTER_DRIVER';
const REGISTER_DRIVERS_LABEL_NAME = 'REGISTER_DRIVER.LABEL_NAME';
const REGISTER_DRIVERS_LABEL_COMPANY = 'REGISTER_DRIVER.LABEL_COMPANY';
const REGISTER_DRIVERS_BUTTON_ADD_COMPANY = 'REGISTER_DRIVER.BUTTON_ADD_COMPANY';
const REGISTER_DRIVERS_LABEL_CARRIER = 'REGISTER_DRIVER.LABEL_CARRIER';
const REGISTER_DRIVERS_LABEL_PHONE = 'REGISTER_DRIVER.LABEL_PHONE';
const REGISTER_DRIVERS_LABEL_EMAIL = 'REGISTER_DRIVER.LABEL_EMAIL';
const REGISTER_DRIVERS_LABEL_POSITION = 'REGISTER_DRIVER.LABEL_POSITION';
const REGISTER_DRIVERS_LABEL_CITY = 'REGISTER_DRIVER.LABEL_CITY';
const REGISTER_DRIVERS_LABEL_STATE = 'REGISTER_DRIVER.LABEL_STATE';
const REGISTER_DRIVERS_LABEL_ZIPCODE = 'REGISTER_DRIVER.LABEL_ZIPCODE';
const REGISTER_DRIVERS_LABEL_COUNTRY = 'REGISTER_DRIVER.LABEL_COUNTRY';
const REGISTER_DRIVERS_LABEL_ACTIVE = 'REGISTER_DRIVER.LABEL_ACTIVE';
const REGISTER_DRIVERS_LABEL_VEHICLE = 'REGISTER_DRIVER.LABEL_VEHICLE';
const REGISTER_DRIVERS_CHECKBOX_VEHICLE = 'REGISTER_DRIVER.CHECKBOX_VEHICLE';
const REGISTER_DRIVERS_LABEL_DRIVER_LICENSE = 'REGISTER_DRIVER.LABEL_DRIVER_LICENSE';
const REGISTER_DRIVERS_LABEL_DRIVER_DESCRIPTION = 'REGISTER_DRIVER.LABEL_DRIVER_DESCRIPTION';
const REGISTER_DRIVERS_LABEL_VEHICLE_INSURANCE = 'REGISTER_DRIVER.LABEL_VEHICLE_INSURANCE';
const REGISTER_DRIVERS_LABEL_STA = 'REGISTER_DRIVER.LABEL_STA';
const REGISTER_DRIVERS_LABEL_PASSWORD = 'REGISTER_DRIVER.LABEL_PASSWORD';
const REGISTER_DRIVERS_LABEL_CONFIRM_PASSWORD = 'REGISTER_DRIVER.LABEL_CONFIRM_PASSWORD';
const REGISTER_DRIVERS_BTN_REGISTER = 'REGISTER_DRIVER.BTN_REGISTER';

// MODAL ADD COMPANY
const MODAL_NEW_COMPANY_TITLE = 'MODAL_NEW_COMPANY.TITLE';
const MODAL_NEW_COMPANY_LABEL_CAMPANY_NAME = 'MODAL_NEW_COMPANY.LABEL_CAMPANY_NAME';
const MODAL_NEW_COMPANY_LABEL_EIN = 'MODAL_NEW_COMPANY.LABEL_EIN';
const MODAL_NEW_COMPANY_LABEL_ADDRESS = 'MODAL_NEW_COMPANY.LABEL_ADDRESS';
const MODAL_NEW_COMPANY_BTN_ENTER = 'MODAL_NEW_COMPANY.BTN_ENTER';
const MODAL_NEW_COMPANY_MSG_SUCCESS = 'MODAL_NEW_COMPANY.MSG_SUCCESS';

// FORGOT PASSWORD
const FORGOT_PASSWORD_TITLE = 'FORGOT_PASSWORD.TITLE';
const FORGOT_PASSWORD_LABEL_EMAIL = 'FORGOT_PASSWORD.LABEL_EMAIL';
const FORGOT_PASSWORD_BTN_CONTINUE = 'FORGOT_PASSWORD.BTN_CONTINUE';
const FORGOT_PASSWORD_BTN_BACK = 'FORGOT_PASSWORD.BTN_BACK';
const FORGOT_PASSWORD_MSG_SUCCESS = 'FORGOT_PASSWORD.MSG_SUCCESS';

// STATUS RECEIVE ORDERS
const STATUS_RECEIVE_ORDERS_ACTIVE = 'STATUS_RECEIVE_ORDERS.ACTIVE';
const STATUS_RECEIVE_ORDERS_DESCRIPTION = 'STATUS_RECEIVE_ORDERS.DESCRIPTION';

// MSG NEW DELIVERY
const MSG_NEW_DELIVERY_BALLON = 'MSG_NEW_DELIVERY.BALLON';
const MSG_NEW_DELIVERY_PICKUP = 'MSG_NEW_DELIVERY.PICKUP';
const MSG_NEW_DELIVERY_DROPOFF = 'MSG_NEW_DELIVERY.DROPOFF';
const MSG_NEW_DELIVERY_BTN_PROPOSAL = 'MSG_NEW_DELIVERY.BTN_PROPOSAL';
const MSG_NEW_DELIVERY_BTN_DECLINE = 'MSG_NEW_DELIVERY.BTN_DECLINE';

//DELIVERY DRIVER
const DELIVERY_DRIVER_DETAILS = 'DELIVERY_DRIVER.DETAILS';
const DELIVERY_DRIVER_PICKUP = 'DELIVERY_DRIVER.PICKUP';
const DELIVERY_DRIVER_DROPOFF = 'DELIVERY_DRIVER.DROPOFF';
const DELIVERY_DRIVER_BTN_SEND_MESSAGE = 'DELIVERY_DRIVER.BTN_SEND_MESSAGE';
const DELIVERY_DRIVER_BTN_IM_HERE = 'DELIVERY_DRIVER.BTN_IM_HERE';
const DELIVERY_DRIVER_BTN_DROP_OFF = 'DELIVERY_DRIVER.BTN_DROP_OFF';

//DROPOFF DETAILS
const DROPOFF_DETAILS_DETAILS = 'DROPOFF_DETAILS.DETAILS';
const DROPOFF_DETAILS_PICKUP = 'DROPOFF_DETAILS.PICKUP';
const DROPOFF_DETAILS_DROPOFF = 'DROPOFF_DETAILS.DROPOFF';
const DROPOFF_DETAILS_BTN_SEND_MESSAGE = 'DROPOFF_DETAILS.BTN_SEND_MESSAGE';
const DROPOFF_DETAILS_BTN_IM_HERE = 'DROPOFF_DETAILS.BTN_IM_HERE';
const DROPOFF_DETAILS_BTN_SIGNATURE = 'DROPOFF_DETAILS.BTN_SIGNATURE';

//DROPOFF SIGNATURE
const DROPOFF_SIGNATURE_TITLE = 'DROPOFF_SIGNATURE.TITLE';
const DROPOFF_SIGNATURE_LABEL_ATTACH_DOCS = 'DROPOFF_SIGNATURE.LABEL_ATTACH_DOCS';
const DROPOFF_SIGNATURE_BTN_UPLOAD = 'DROPOFF_SIGNATURE.BTN_UPLOAD';
const DROPOFF_SIGNATURE_LABEL_ATTACH_PICTURES = 'DROPOFF_SIGNATURE.LABEL_ATTACH_PICTURES';
const DROPOFF_SIGNATURE_LABEL_CONTACT_SIGNATURE = 'DROPOFF_SIGNATURE.LABEL_CONTACT_SIGNATURE';
const DROPOFF_SIGNATURE_LABEL_DATE = 'DROPOFF_SIGNATURE.LABEL_DATE';
const DROPOFF_SIGNATURE_LABEL_TIME = 'DROPOFF_SIGNATURE.LABEL_TIME';
const DROPOFF_SIGNATURE_LABEL_LOCATION = 'DROPOFF_SIGNATURE.LABEL_LOCATION';
const DROPOFF_SIGNATURE_LABEL_NAME = 'DROPOFF_SIGNATURE.LABEL_NAME';
const DROPOFF_SIGNATURE_BTN_FINISH = 'DROPOFF_SIGNATURE.BTN_FINISH';

// MODAL SEND OFFER
const MODAL_SEND_OFFER_TITLE = 'MODAL_SEND_OFFER.TITLE';
const MODAL_SEND_OFFER_LABEL_REQUESTED = 'MODAL_SEND_OFFER.LABEL_REQUESTED';
const MODAL_SEND_OFFER_LABEL_PICKUP = 'MODAL_SEND_OFFER.LABEL_PICKUP';
const MODAL_SEND_OFFER_LABEL_DROPOFF = 'MODAL_SEND_OFFER.LABEL_DROPOFF';
const MODAL_SEND_OFFER_LABEL_CALCULATION = 'MODAL_SEND_OFFER.LABEL_CALCULATION';
const MODAL_SEND_OFFER_LABEL_TELL = 'MODAL_SEND_OFFER.LABEL_TELL';
const MODAL_SEND_OFFER_LABEL_HOW_MUCH = 'MODAL_SEND_OFFER.LABEL_HOW_MUCH';
const MODAL_SEND_OFFER_LABEL_INPUT = 'MODAL_SEND_OFFER.LABEL_INPUT';
const MODAL_SEND_OFFER_BTN_SEND_OFFER = 'MODAL_SEND_OFFER.BTN_SEND_OFFER';

// MODAL_PROPOSAL_ACCEPTED
const MODAL_PROPOSAL_ACCEPTED_TITLE = 'MODAL_PROPOSAL_ACCEPTED.TITLE';
const MODAL_PROPOSAL_ACCEPTED_LABEL_ACCEPTED = 'MODAL_PROPOSAL_ACCEPTED.LABEL_ACCEPTED';
const MODAL_PROPOSAL_ACCEPTED_LABEL_SERVICE = 'MODAL_PROPOSAL_ACCEPTED.LABEL_SERVICE';
const MODAL_PROPOSAL_ACCEPTED_LABEL_PICKUP = 'MODAL_PROPOSAL_ACCEPTED.LABEL_PICKUP';
const MODAL_PROPOSAL_ACCEPTED_LABEL_DROPOFF = 'MODAL_PROPOSAL_ACCEPTED.LABEL_DROPOFF';
const MODAL_PROPOSAL_ACCEPTED_LABEL_PROGRESS = 'MODAL_PROPOSAL_ACCEPTED.LABEL_PROGRESS';
const MODAL_PROPOSAL_ACCEPTED_BTN_CANCEL = 'MODAL_PROPOSAL_ACCEPTED.BTN_CANCEL';
const MODAL_PROPOSAL_ACCEPTED_BTN_OK = 'MODAL_PROPOSAL_ACCEPTED.BTN_OK';

// MODAL ADD USER
const MODAL_ADD_USER_TITLE = 'MODAL_ADD_USER.TITLE';
const MODAL_ADD_USER_LABEL_NAME = 'MODAL_ADD_USER.LABEL_NAME';
const MODAL_ADD_USER_LABEL_EMAIL = 'MODAL_ADD_USER.LABEL_EMAIL';
const MODAL_ADD_USER_LABEL_PHONE = 'MODAL_ADD_USER.LABEL_PHONE';
const MODAL_ADD_USER_BTN_ADD = 'MODAL_ADD_USER.BTN_ADD';
const MODAL_ADD_USER_LABEL_USER = 'MODAL_ADD_USER.LABEL_USER';
const MODAL_ADD_USER_LABEL = 'MODAL_ADD_USER.LABEL';
const MODAL_ADD_USER_BTN_EDIT_LIST = 'MODAL_ADD_USER.BTN_EDIT_LIST';
const MODAL_ADD_USER_LABEL_USER_ADDED = 'MODAL_ADD_USER.LABEL_USER_ADDED';

export {
  BTN_LOGIN,
  BTN_REGISTER,
  BTN_HOME,
  BTN_COURIER,
  BTN_CONSULTING,
  BTN_HELPING_LIVES,
  BTN_CONTACT_US,
  TITLE_MAIN,
  LOGISTIC_MAIN,
  CONTENT_MAIN,
  TEXT_FLAG_PT,
  TEXT_FLAG_EN,
  TEXT_FLAG_ES,
  LABEL_PASSWORD,
  LOGIN_MSG_ERROR,
  FORGOT_PASSWORD,
  BTN_ENTER,
  BTN_BACK,
  BTN_DRIVER,
  BTN_USER,
  LABEL_REGISTER,
  LABEL_COMPANY,
  LABEL_NAME,
  LABEL_EMAIL,
  LABEL_PHONE,
  ADD_MORE_USERS,
  LABEL_ADRESS,
  LABEL_ZIPCODE,
  LABEL_CITY,
  LABEL_STATE,
  LABEL_COUNTRY,
  LABEL_PASSWORD_REGISTER,
  LABEL_CONFIRM_PASSWORD,
  BTN_REGISTER_REGISTER,
  BTN_BACK_REGISTER,
  REGISTER_MSG_EMPTY_FIELDS,
  REGISTER_MSG_PASSWORD_NOT_MATCH,
  REGISTER_MSG_USER_REGISTERED_SUCCESS,
  REGISTER_MSG_USER_REGISTERED_ERROR,
  ROUTE_NOT_FOUND_TITLE,
  ROUTE_NOT_FOUND_CONTENT,
  ROUTE_NOT_FOUND_BTN_BACK,
  BTN_CREATE_ORDER,
  STATUS_OPEN,
  LABEL_YOUR_DELIVERIES,
  STATUS_PROGRESS,
  STATUS_COMPLETE,
  TITLE_ORDERS,
  TITLE_DATE,
  TITLE_FROM,
  TITLE_TO,
  TITLE_DRIVER,
  TITLE_LOAD,
  BTN_SEE_MORE,
  PATH_SEE_MORE,
  PATH_HOME,
  TITLE_OPEN_REQUEST,
  MSG_UNANSWERED,
  TITLE_PICKUP,
  TITLE_DROPOFF,
  MSG_PICKUP_DETAILS,
  TITLE_BILL_TO,
  TITLE_DATE_ORDER_DETAIL,
  TITLE_TIME,
  TITLE_COMPANY_NAME,
  TITLE_EMAIL,
  TITLE_PHONE,
  TITLE_ADRESS,
  TITLE_ZIPCODE,
  TITLE_CITY,
  TITLE_STATE,
  TITLE_DELIVERY_DETAILS,
  TITLE_CONTACT_NAME,
  TITLE_ORDER_DETAILS,
  TITLE_BTN_CANCEL_ORDER,
  TITLE_BTN_EDIT_OFFER,
  ORDER_DETAILS_BTN_BACK,
  ORDER_DETAILS_MSG_CANCELED_ORDER,
  TITLE_NEW_OFFER,
  MSG_WILL_CHANGE,
  MSG_FOR_SERVICE,
  BTN_ACCEPT_OFFER,
  BTN_CANCEL_OFFER,
  MODAL_NEW_OFFER_LABEL_PICKUP,
  MODAL_NEW_OFFER_LABEL_DROPOFF,
  TITLE_CANCEL_ORDER,
  MSG_CANCEL,
  BTN_AWARE,
  TITLE_ORDER_CANCELED,
  MSG_ORDER_CANCELED,
  MSG_OPTIONAL_CAR,
  MSG_OPTIONAL_DRIVER,
  MSG_OPTIONAL_PLACE,
  MSG_OPTIONAL_DATES,
  MSG_OPTIONAL_RUDE,
  MSG_OPTIONAL_OTHER,
  BTN_SEND,
  BREAD_CRUMBS_NEW_ORDER,
  LABEL_BILL_TO_PICKUP,
  LABEL_DATE_PICKUP,
  LABEL_TIME_PICKUP,
  LABEL_COMPANY_NAME_PICKUP,
  LABEL_EMAIL_PICKUP,
  LABEL_PHONE_PICKUP,
  LABEL_ADRESS_PICKUP,
  LABEL_ZIPCODE_PICKUP,
  LABEL_CITY_PICKUP,
  LABEL_STATE_PICKUP,
  LABEL_CONTACT_NAME_PICKUP,
  BTN_NEXT_PICKUP,
  LABEL_DATE_DELIVERY,
  LABEL_TIME_DELIVERY,
  LABEL_COMPANY_NAME_DELIVERY,
  LABEL_EMAIL_DELIVERY,
  LABEL_PHONE_DELIVERY,
  LABEL_ADRESS_DELIVERY,
  LABEL_ZIPCODE_DELIVERY,
  LABEL_CITY_DELIVERY,
  LABEL_STATE_DELIVERY,
  LABEL_CONTACT_NAME_DELIVERY,
  BTN_NEXT_DELIVERY,
  BTN_BACK_DELIVERY,
  TITLE_PICKING_UP_01,
  TITLE_PICKING_UP_02,
  TITLE_PICKING_UP_03,
  TITLE_PICKING_UP_04,
  TITLE_DIMENSIONS_01,
  TITLE_DIMENSIONS_02,
  TITLE_DIMENSIONS_03,
  TITLE_DIMENSIONS_04,
  TITLE_CARGO,
  DIMENSION_FEET,
  DIMENSION_CENTIMETER,
  DIMENSION_LBS,
  DIMENSION_KGS,
  TOTAL_WEIGHT,
  LABEL_HIGHT,
  LABEL_WIDTH,
  LABEL_DEPTH,
  LABEL_WEIGHT,
  BTN_TAKE_PICTURE,
  TITLE_PURCHASE_ORDER_01,
  TITLE_PURCHASE_ORDER_02,
  TITLE_PURCHASE_ORDER_03,
  TITLE_PURCHASE_ORDER_04,
  LABEL_INVOICE_NUMBER,
  TITLE_OBSERVATION,
  LABEL_OBSERVATION,
  SELECT_TYPE_CARGO,
  SELECT_TYPE_DOCS,
  SELECT_TYPE_CARGO_DOCS,
  BTN_NEXT_ORDERS_ORDERS_DETAIL,
  BTN_BACK_ORDERS_ORDERS_DETAIL,
  TITLE_CONFIRMATION_PICKUP_DETAILS,
  TITLE_CONFIRMATION_DELIVERY_DETAILS,
  TITLE_CONFIRMATION_ORDER_DETAILS,
  LABEL_BILL_TO_CONFIRMATION,
  LABEL_DATE_CONFIRMATION,
  LABEL_TIME_CONFIRMATION,
  LABEL_COMPANY_NAME_CONFIRMATION,
  LABEL_CONTACT_NAME_CONFIRMATION,
  LABEL_EMAIL_CONFIRMATION,
  LABEL_PHONE_CONFIRMATION,
  LABEL_ADRESS_CONFIRMATION,
  LABEL_ZIPCODE_CONFIRMATION,
  LABEL_CITY_CONFIRMATION,
  LABEL_STATE_CONFIRMATION,
  BTN_FINISH_ORDER,
  TITLE_CONFIRMATION_PROOF_DELIVERY,
  LABEL_ATTACH_DOCS,
  BTN_CONFIRMATION_UPLOAD_DOCS,
  LABEL_ATTACH_PICTURES_CARGO,
  LABEL_CONTATCT_SIGNTURE,
  LABEL_CONFIRMATION_NAME,
  LABEL_CONFIRMATION_DATE,
  LABEL_CONFIRMATION_TIME,
  LABEL_CONFIRMATION_LOCATION,
  BTN_BACK_CONFIRMATION,
  BTN_NEW_ORDER_CONFIRMATION,
  MSG_CREATE_SUCCESS_ORDER_CONFIRMATION,
  MSG_CREATE_FAILED_ORDER_CONFIRMATION,
  STEP_PICKUP_DETAILS,
  STEP_DELIVERY_DETAILS,
  STEP_ORDERS_DETAILS,
  STEP_CONFIRMATION,
  REGISTER_DRIVERS_TITLE,
  REGISTER_DRIVERS_LABEL_NAME,
  REGISTER_DRIVERS_LABEL_COMPANY,
  REGISTER_DRIVERS_BUTTON_ADD_COMPANY,
  REGISTER_DRIVERS_LABEL_CARRIER,
  REGISTER_DRIVERS_LABEL_PHONE,
  REGISTER_DRIVERS_LABEL_EMAIL,
  REGISTER_DRIVERS_LABEL_POSITION,
  REGISTER_DRIVERS_LABEL_CITY,
  REGISTER_DRIVERS_LABEL_STATE,
  REGISTER_DRIVERS_LABEL_ZIPCODE,
  REGISTER_DRIVERS_LABEL_COUNTRY,
  REGISTER_DRIVERS_LABEL_ACTIVE,
  REGISTER_DRIVERS_LABEL_VEHICLE,
  REGISTER_DRIVERS_CHECKBOX_VEHICLE,
  REGISTER_DRIVERS_LABEL_DRIVER_LICENSE,
  REGISTER_DRIVERS_LABEL_DRIVER_DESCRIPTION,
  REGISTER_DRIVERS_LABEL_VEHICLE_INSURANCE,
  REGISTER_DRIVERS_LABEL_STA,
  REGISTER_DRIVERS_LABEL_PASSWORD,
  REGISTER_DRIVERS_LABEL_CONFIRM_PASSWORD,
  REGISTER_DRIVERS_BTN_REGISTER,
  MODAL_NEW_COMPANY_TITLE,
  MODAL_NEW_COMPANY_LABEL_CAMPANY_NAME,
  MODAL_NEW_COMPANY_LABEL_EIN,
  MODAL_NEW_COMPANY_LABEL_ADDRESS,
  MODAL_NEW_COMPANY_BTN_ENTER,
  MODAL_NEW_COMPANY_MSG_SUCCESS,
  FORGOT_PASSWORD_TITLE,
  FORGOT_PASSWORD_LABEL_EMAIL,
  FORGOT_PASSWORD_BTN_CONTINUE,
  FORGOT_PASSWORD_BTN_BACK,
  FORGOT_PASSWORD_MSG_SUCCESS,
  STATUS_RECEIVE_ORDERS_ACTIVE,
  STATUS_RECEIVE_ORDERS_DESCRIPTION,
  MSG_NEW_DELIVERY_BALLON,
  MSG_NEW_DELIVERY_PICKUP,
  MSG_NEW_DELIVERY_DROPOFF,
  MSG_NEW_DELIVERY_BTN_PROPOSAL,
  MSG_NEW_DELIVERY_BTN_DECLINE,
  DELIVERY_DRIVER_DETAILS,
  DELIVERY_DRIVER_PICKUP,
  DELIVERY_DRIVER_DROPOFF,
  DELIVERY_DRIVER_BTN_SEND_MESSAGE,
  DELIVERY_DRIVER_BTN_IM_HERE,
  DELIVERY_DRIVER_BTN_DROP_OFF,
  DROPOFF_DETAILS_DETAILS,
  DROPOFF_DETAILS_PICKUP,
  DROPOFF_DETAILS_DROPOFF,
  DROPOFF_DETAILS_BTN_SEND_MESSAGE,
  DROPOFF_DETAILS_BTN_IM_HERE,
  DROPOFF_DETAILS_BTN_SIGNATURE,
  DROPOFF_SIGNATURE_TITLE,
  DROPOFF_SIGNATURE_LABEL_ATTACH_DOCS,
  DROPOFF_SIGNATURE_BTN_UPLOAD,
  DROPOFF_SIGNATURE_LABEL_ATTACH_PICTURES,
  DROPOFF_SIGNATURE_LABEL_CONTACT_SIGNATURE,
  DROPOFF_SIGNATURE_LABEL_DATE,
  DROPOFF_SIGNATURE_LABEL_TIME,
  DROPOFF_SIGNATURE_LABEL_LOCATION,
  DROPOFF_SIGNATURE_LABEL_NAME,
  DROPOFF_SIGNATURE_BTN_FINISH,
  MODAL_SEND_OFFER_TITLE,
  MODAL_SEND_OFFER_LABEL_REQUESTED,
  MODAL_SEND_OFFER_LABEL_PICKUP,
  MODAL_SEND_OFFER_LABEL_DROPOFF,
  MODAL_SEND_OFFER_LABEL_CALCULATION,
  MODAL_SEND_OFFER_LABEL_TELL,
  MODAL_SEND_OFFER_LABEL_HOW_MUCH,
  MODAL_SEND_OFFER_LABEL_INPUT,
  MODAL_SEND_OFFER_BTN_SEND_OFFER,
  MODAL_PROPOSAL_ACCEPTED_TITLE,
  MODAL_PROPOSAL_ACCEPTED_LABEL_ACCEPTED,
  MODAL_PROPOSAL_ACCEPTED_LABEL_SERVICE,
  MODAL_PROPOSAL_ACCEPTED_LABEL_PICKUP,
  MODAL_PROPOSAL_ACCEPTED_LABEL_DROPOFF,
  MODAL_PROPOSAL_ACCEPTED_LABEL_PROGRESS,
  MODAL_PROPOSAL_ACCEPTED_BTN_CANCEL,
  MODAL_PROPOSAL_ACCEPTED_BTN_OK,
  MODAL_ADD_USER_TITLE,
  MODAL_ADD_USER_LABEL_NAME,
  MODAL_ADD_USER_LABEL_EMAIL,
  MODAL_ADD_USER_LABEL_PHONE,
  MODAL_ADD_USER_BTN_ADD,
  MODAL_ADD_USER_LABEL_USER,
  MODAL_ADD_USER_LABEL,
  MODAL_ADD_USER_BTN_EDIT_LIST,
  MODAL_ADD_USER_LABEL_USER_ADDED,
  REGISTER_USER_AUTH_SLICE,
  LOGIN_USER_AUTH_SLICE,
  LIST_ORDERS_SLICE,
  CREATE_ORDER_SLICE,
  CANCEL_ORDER_SLICE,
  TITLE_TOTAL_OBJ,
  TITLE_VOLUME,
  BTN_TITLE_BUTTOM_IMAGE_DOWNLOAD,
  STATUS_CANCELED,
  STATUS_QUEUED,
  TITLE_USER
};
